# Generated by Django 4.0 on 2023-08-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfacesApi', '0003_ecu_info_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='deleted',
        ),
    ]
